// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfmighvtybafzumnuorf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmbWlnaHZ0eWJhZnp1bW51b3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTIyOTIsImV4cCI6MjA2NDQ2ODI5Mn0.VTygF9di1gwg-kzeQd8io5LHLY776_0BZXB89wT40Q0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});